(function(){
const K={profile:'dalLeadProfile',saved:'dalSavedItems',events:'dalLeadEvents'};
const programMap={
'computer-science.html':['cs','Computer Science','BCS'],'marine-biology.html':['marine','Marine Biology','BSc / BA'],'commerce.html':['commerce','Commerce','BComm'],'nursing.html':['nursing','Nursing','BScN'],'engineering.html':['eng','Engineering','BEng'],'psychology.html':['psych','Psychology','BSc / BA'],'ocean-sciences.html':['ocean','Ocean Sciences','BSc / BA'],'environmental-science.html':['env','Environmental Science','BSc / BA'],'arts.html':['arts','Arts','BA'],'kinesiology.html':['kine','Kinesiology','BSc'],'bioveterinary-science.html':['biovet','Bioveterinary Science','BSc'],'international-development-studies.html':['ids','International Development Studies','BA'],'economics.html':['econ','Economics','BA / BSc'],'biochemistry-molecular-biology.html':['biochem','Biochemistry & Molecular Biology','BSc']};
let pending=null;
function read(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch(e){return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function profile(){return read(K.profile,null)}
function saved(){return read(K.saved,[])}
function event(type,data={}){const a=read(K.events,[]);a.push({type,at:new Date().toISOString(),page:location.pathname.split('/').pop()||'index.html',...data});write(K.events,a)}
function currentProgram(){const file=location.pathname.split('/').pop();const m=programMap[file];if(m)return {id:m[0],name:m[1],degree:m[2],page:file};const h=document.querySelector('h1');return h?{id:file||'program',name:h.textContent.trim(),degree:'',page:file}:null}
function saveItem(item){const a=saved();if(!a.some(x=>x.id===item.id&&x.type===item.type)){a.push({...item,savedAt:new Date().toISOString()});write(K.saved,a);event(item.type+'_saved',{itemId:item.id,itemName:item.name})}syncUI();toast(item.name+' saved to My Dal')}
function removeItem(id,type='program'){write(K.saved,saved().filter(x=>!(x.id===id&&x.type===type)));event(type+'_removed',{itemId:id});syncUI();toast('Removed from My Dal')}
function isSaved(id,type='program'){return saved().some(x=>x.id===id&&x.type===type)}
function requireAccount(item){const p=profile();if(p&&p.verified){saveItem(item);return true}pending=item;openAccount();return false}
function modal(){let el=document.getElementById('dalLeadModal');if(el)return el;el=document.createElement('div');el.id='dalLeadModal';el.innerHTML=`<div class="dal-lead-sheet" role="dialog" aria-modal="true"><button class="dal-x" aria-label="Close">×</button><div id="dalLeadBody"></div></div>`;document.body.appendChild(el);el.addEventListener('click',e=>{if(e.target===el||e.target.classList.contains('dal-x'))closeModal()});return el}
function injectStyles(){if(document.getElementById('dalLeadStyles'))return;const s=document.createElement('style');s.id='dalLeadStyles';s.textContent=`#dalLeadModal{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.72);display:none;align-items:center;justify-content:center;padding:20px}.dal-lead-sheet{width:min(520px,100%);background:#242424;color:#fff;border:1px solid rgba(255,255,255,.14);border-radius:24px;padding:28px;box-shadow:0 28px 90px rgba(0,0,0,.5);position:relative}.dal-x{position:absolute;right:18px;top:14px;border:0;background:transparent;color:#aaa;font-size:28px;cursor:pointer}.dal-kicker{color:#FFD400;text-transform:uppercase;letter-spacing:1.4px;font-size:11px;font-weight:900}.dal-lead-sheet h2{font-size:30px;line-height:1.05;margin:8px 0 9px}.dal-lead-sheet p{color:#c9c5ba;line-height:1.5}.dal-form{display:grid;gap:12px;margin-top:20px}.dal-form label{font-size:12px;color:#d8d4ca}.dal-form input{width:100%;margin-top:5px;padding:13px 14px;border-radius:12px;border:1px solid rgba(255,255,255,.16);background:#151515;color:#fff;outline:none}.dal-form input:focus{border-color:#FFD400}.dal-primary{border:0;border-radius:999px;background:#FFD400;color:#242424;padding:12px 17px;font-weight:900;cursor:pointer}.dal-secondary{border:1px solid rgba(255,255,255,.16);border-radius:999px;background:transparent;color:white;padding:11px 16px;font-weight:800;cursor:pointer}.dal-consent{display:flex!important;gap:9px;align-items:flex-start;color:#aaa!important;line-height:1.4}.dal-consent input{width:auto;margin:2px 0 0}.dal-note{font-size:11px;color:#8f8b82!important}.dal-code{display:flex;gap:8px}.dal-code input{text-align:center;font-size:22px;letter-spacing:5px}.dal-success{padding:13px;border-radius:14px;background:rgba(255,212,0,.10);border:1px solid rgba(255,212,0,.28)}.dal-toast{position:fixed;right:22px;bottom:22px;z-index:10000;background:#fff;color:#222;padding:12px 16px;border-radius:12px;box-shadow:0 12px 40px rgba(0,0,0,.3)}.dal-card-save{position:absolute;z-index:6;right:11px;top:11px;width:38px;height:38px;border-radius:50%;border:1px solid rgba(255,255,255,.28);background:rgba(18,18,18,.72);color:white;font-size:18px;display:grid;place-items:center;cursor:pointer;backdrop-filter:blur(7px)}.dal-card-save.saved{background:#FFD400;color:#242424;border-color:#FFD400}.dal-account{white-space:nowrap}@media(max-width:600px){.dal-lead-sheet{padding:24px 20px}}`;document.head.appendChild(s)}
function openAccount(){injectStyles();const m=modal(),b=m.querySelector('#dalLeadBody'),p=profile();b.innerHTML=`<div class="dal-kicker">Save it. Keep exploring.</div><h2>Create your My Dal profile.</h2><p>Save programs and pick up where you left off on another visit.</p><form class="dal-form" id="dalCreateForm"><label>First name<input name="first" required autocomplete="given-name" value="${p?.first||''}"></label><label>Email address<input name="email" type="email" required autocomplete="email" value="${p?.email||''}"></label><label>Home city<input name="city" required autocomplete="address-level2" value="${p?.city||''}"></label><label class="dal-consent"><input name="marketing" type="checkbox"> <span>Keep me updated about programs, deadlines, events and opportunities at Dal.</span></label><button class="dal-primary">Save my list</button><p class="dal-note">Prototype: this profile is stored only in this browser. In production, the record and engagement events would be sent to Dal’s recruitment CRM / Slate.</p></form>`;m.style.display='flex';b.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const d={first:f.get('first').trim(),email:f.get('email').trim(),city:f.get('city').trim(),marketing:f.get('marketing')==='on',verified:false,createdAt:new Date().toISOString()};write(K.profile,d);event('lead_created',{email:d.email,city:d.city,marketingConsent:d.marketing});showVerify()}}
function showVerify(){const m=modal(),b=m.querySelector('#dalLeadBody'),p=profile();b.innerHTML=`<div class="dal-kicker">Verify your email</div><h2>Check ${p.email}</h2><p>For the prototype, use code <b style="color:white">246810</b>. In production this would be sent by email before the profile becomes active.</p><form class="dal-form" id="dalVerifyForm"><label>Verification code<div class="dal-code"><input name="code" inputmode="numeric" maxlength="6" placeholder="000000" required></div></label><button class="dal-primary">Verify & save</button><button type="button" class="dal-secondary" id="dalBack">Change email</button></form>`;b.querySelector('#dalBack').onclick=openAccount;b.querySelector('form').onsubmit=e=>{e.preventDefault();const code=new FormData(e.target).get('code');if(code!=='246810'){toast('Use prototype code 246810');return}const q=profile();q.verified=true;q.verifiedAt=new Date().toISOString();write(K.profile,q);event('email_verified',{email:q.email});m.querySelector('#dalLeadBody').innerHTML=`<div class="dal-kicker">You’re in</div><h2>Welcome to My Dal, ${escapeHtml(q.first)}.</h2><div class="dal-success">Your profile is verified. Future saves happen instantly on this device.</div><div style="display:flex;gap:9px;margin-top:20px"><a class="dal-primary" href="my-dal.html" style="text-decoration:none">Open My Dal</a><button class="dal-secondary" id="dalContinue">Keep exploring</button></div>`;m.querySelector('#dalContinue').onclick=()=>{closeModal();if(pending){saveItem(pending);pending=null}};if(pending){saveItem(pending);pending=null}syncUI()}}
function openSignIn(){injectStyles();const m=modal(),b=m.querySelector('#dalLeadBody'),p=profile();if(p&&p.verified){location.href='my-dal.html';return}b.innerHTML=`<div class="dal-kicker">Welcome back</div><h2>Sign in to My Dal.</h2><p>Enter the email address you used to save your results.</p><form class="dal-form"><label>Email address<input name="email" type="email" required></label><button class="dal-primary">Continue</button><button type="button" class="dal-secondary" id="dalNew">Create a profile</button></form><p class="dal-note">Prototype sign-in recognizes the profile stored in this browser.</p>`;m.style.display='flex';b.querySelector('#dalNew').onclick=openAccount;b.querySelector('form').onsubmit=e=>{e.preventDefault();const email=new FormData(e.target).get('email').trim().toLowerCase();const q=profile();if(q&&q.email.toLowerCase()===email&&q.verified){event('login',{email:q.email});closeModal();syncUI();location.href='my-dal.html'}else toast('No verified prototype profile found on this device')}}
function closeModal(){const m=document.getElementById('dalLeadModal');if(m)m.style.display='none'}
function syncUI(){const p=profile();document.querySelectorAll('[data-dal-account]').forEach(el=>{el.textContent=p&&p.verified?`Hi, ${p.first} · My Dal`:'Sign in';el.onclick=e=>{e.preventDefault();p&&p.verified?location.href='my-dal.html':openSignIn()}});document.querySelectorAll('.dal-card-save').forEach(b=>{b.classList.toggle('saved',isSaved(b.dataset.id));b.textContent=isSaved(b.dataset.id)?'✓':'♡'});const cp=currentProgram();if(cp){document.querySelectorAll('button,a').forEach(el=>{if(/save/i.test(el.textContent||'')&&!el.closest('#dalLeadModal')&&!el.classList.contains('dal-card-save')){if(isSaved(cp.id)){if(/save program|save$/i.test(el.textContent.trim()))el.textContent='✓ Saved'} }})}}
function attachProgramCards(){document.querySelectorAll('.card').forEach(c=>{if(c.querySelector('.dal-card-save'))return;const title=c.querySelector('h3')?.textContent.trim();if(!title)return;const p=Object.entries(programMap).find(([,v])=>v[1]===title);if(!p)return;const b=document.createElement('button');b.className='dal-card-save';b.dataset.id=p[1][0];b.title='Save '+title;b.textContent=isSaved(p[1][0])?'✓':'♡';if(isSaved(p[1][0]))b.classList.add('saved');b.onclick=e=>{e.preventDefault();e.stopPropagation();const item={type:'program',id:p[1][0],name:title,degree:p[1][2],page:p[0]};isSaved(item.id)?removeItem(item.id):requireAccount(item)};c.appendChild(b)})}
function interceptSaves(){document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el||el.closest('#dalLeadModal')||el.classList.contains('dal-card-save'))return;const txt=(el.textContent||'').trim();if(!/^♡?\s*Save|^✓\s*Saved|Save Marine Biology|Save program/i.test(txt))return;const cp=currentProgram();if(!cp)return;e.preventDefault();e.stopImmediatePropagation();const item={type:'program',...cp};isSaved(item.id)?removeItem(item.id):requireAccount(item)},true)}
function toast(msg){const x=document.createElement('div');x.className='dal-toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function init(){injectStyles();interceptSaves();attachProgramCards();syncUI();new MutationObserver(()=>attachProgramCards()).observe(document.body,{childList:true,subtree:true})}
window.DalLead={profile,saved,events:()=>read(K.events,[]),requireAccount,saveItem,removeItem,isSaved,openAccount,openSignIn,syncUI};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();