(function(){
const ACCOUNT='dal_prospect_account_v1', LEADS='dal_prospect_leads_v1', CODE='246810';
let pending=null;
const css=`
.lead-modal{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.72);display:none;align-items:center;justify-content:center;padding:20px}.lead-modal.open{display:flex}.lead-box{width:min(560px,100%);max-height:90vh;overflow:auto;background:#242424;color:#fff;border:1px solid rgba(255,255,255,.16);border-radius:24px;box-shadow:0 28px 80px rgba(0,0,0,.5);padding:26px}.lead-top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.lead-kicker{color:#FFD400;text-transform:uppercase;font-size:11px;letter-spacing:1.5px;font-weight:900}.lead-box h2{font-size:30px;letter-spacing:-1px;margin:7px 0 8px}.lead-box p{color:#c9c5bb;line-height:1.5}.lead-close{border:0;background:transparent;color:#aaa;font-size:26px;cursor:pointer}.lead-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.lead-field{display:flex;flex-direction:column;gap:6px;margin:10px 0}.lead-field.full{grid-column:1/-1}.lead-field label{font-size:12px;color:#d8d4ca;font-weight:750}.lead-field input{width:100%;border-radius:11px;border:1px solid rgba(255,255,255,.15);background:#171717;color:white;padding:12px 13px;outline:none}.lead-field input:focus{border-color:#FFD400}.lead-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.lead-btn{border:0;border-radius:999px;padding:11px 16px;font-weight:850;cursor:pointer}.lead-primary{background:#FFD400;color:#242424}.lead-secondary{background:transparent;color:white;border:1px solid rgba(255,255,255,.18)}.lead-note{font-size:11px;color:#96928a!important;margin:14px 0 0!important}.lead-error{font-size:12px;color:#ff9d88;min-height:18px}.lead-code{padding:13px;border-radius:12px;background:rgba(255,212,0,.08);border:1px solid rgba(255,212,0,.24);margin:14px 0;color:#eee}.lead-code b{color:#FFD400;letter-spacing:2px}.saved-list{display:grid;gap:9px;margin-top:15px}.saved-item{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:13px 14px;border:1px solid rgba(255,255,255,.12);border-radius:14px;background:#1d1d1d}.saved-item b{display:block}.saved-item small{display:block;color:#aaa;margin-top:3px}.saved-item button{border:0;background:transparent;color:#aaa;cursor:pointer}.account-chip{white-space:nowrap}@media(max-width:600px){.lead-grid{grid-template-columns:1fr}.lead-field.full{grid-column:auto}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const modal=document.createElement('div');modal.className='lead-modal';modal.id='leadModal';modal.innerHTML='<div class="lead-box" id="leadBox"></div>';document.body.appendChild(modal);
modal.addEventListener('click',e=>{if(e.target===modal)close()});
function account(){try{return JSON.parse(localStorage.getItem(ACCOUNT)||'null')}catch(e){return null}}
function leads(){try{return JSON.parse(localStorage.getItem(LEADS)||'{}')}catch(e){return {}}}
function saveLeads(v){localStorage.setItem(LEADS,JSON.stringify(v))}
function close(){modal.classList.remove('open');pending=null}
function open(){modal.classList.add('open')}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function renderRegister(item){open();leadBox.innerHTML=`<div class="lead-top"><div><div class="lead-kicker">Save your progress</div><h2>Keep this for later.</h2></div><button class="lead-close" onclick="LeadGen.close()">×</button></div><p>Create a very light Dal profile so your programs and planning results can come with you.</p><div class="lead-grid"><div class="lead-field"><label>First name</label><input id="lgFirst" autocomplete="given-name"></div><div class="lead-field"><label>Last name</label><input id="lgLast" autocomplete="family-name"></div><div class="lead-field full"><label>Email</label><input id="lgEmail" type="email" autocomplete="email"></div><div class="lead-field full"><label>Home city</label><input id="lgCity" autocomplete="address-level2" placeholder="e.g. Ottawa, ON"></div></div><div class="lead-error" id="lgError"></div><div class="lead-actions"><button class="lead-btn lead-primary" onclick="LeadGen.sendCode()">Continue →</button><button class="lead-btn lead-secondary" onclick="LeadGen.signIn()">I already have a profile</button></div><p class="lead-note">Prototype only. In production this would create or update a prospect record through a secure integration into Slate and use a real email verification service.</p>`;pending=item}
function sendCode(){const f=lgFirst.value.trim(),l=lgLast.value.trim(),e=lgEmail.value.trim().toLowerCase(),c=lgCity.value.trim();if(!f||!l||!validEmail(e)){lgError.textContent='Add your name and a valid email address.';return}pending={item:pending,profile:{first:f,last:l,email:e,city:c}};leadBox.innerHTML=`<div class="lead-top"><div><div class="lead-kicker">Verify your email</div><h2>Check ${esc(e)}</h2></div><button class="lead-close" onclick="LeadGen.close()">×</button></div><p>We would send a six-digit code to confirm the address before creating the prospect record.</p><div class="lead-code">Prototype verification code: <b>${CODE}</b></div><div class="lead-field"><label>Verification code</label><input id="lgCode" inputmode="numeric" maxlength="6"></div><div class="lead-error" id="lgError"></div><div class="lead-actions"><button class="lead-btn lead-primary" onclick="LeadGen.verify()">Verify & save →</button><button class="lead-btn lead-secondary" onclick="LeadGen.close()">Cancel</button></div>`}
function verify(){if((lgCode.value||'').trim()!==CODE){lgError.textContent='That code does not match the prototype code above.';return}const p=pending.profile;const a={...p,verified:true,createdAt:new Date().toISOString(),source:'Discover Dal prototype'};localStorage.setItem(ACCOUNT,JSON.stringify(a));const all=leads();all[p.email]=all[p.email]||{profile:a,saved:[]};all[p.email].profile=a;saveLeads(all);const item=pending.item;pending=null;if(item)addItem(item);updateAccountUI();showSaved('Your profile is ready. We saved that for you.')}
function normalizeItem(item){if(typeof item==='string')return {type:'item',id:item,label:item,url:location.href,savedAt:new Date().toISOString()};return {...item,savedAt:new Date().toISOString(),url:item.url||location.href}}
function addItem(item){const a=account();if(!a)return renderRegister(item);const all=leads();all[a.email]=all[a.email]||{profile:a,saved:[]};const n=normalizeItem(item);const arr=all[a.email].saved||[];const key=n.id||n.label;if(!arr.some(x=>(x.id||x.label)===key))arr.unshift(n);all[a.email].saved=arr;saveLeads(all);updateAccountUI();markSaved(n);return n}
function save(item){if(account())return addItem(item);renderRegister(item)}
function inferItem(target){const body=document.body.dataset.program;let label='Saved result',id='saved-'+location.pathname;if(body){const title=document.querySelector('h1')?.textContent?.trim()||body;return {type:'program',id:'program:'+body,label:title,url:location.href}}if(location.pathname.includes('marine-biology'))return {type:'program',id:'program:marine',label:'Marine Biology',url:location.href};const card=target.closest('.card');if(card){const name=card.querySelector('h3')?.textContent?.trim()||'Program';return {type:'program',id:'program:'+name.toLowerCase().replace(/\W+/g,'-'),label:name,url:card.getAttribute('data-url')||location.href}}return {type:'result',id:id,label:document.title.replace(' — Discover Dal',''),url:location.href}}
function signIn(){open();pending=null;leadBox.innerHTML=`<div class="lead-top"><div><div class="lead-kicker">Welcome back</div><h2>Retrieve your saved results.</h2></div><button class="lead-close" onclick="LeadGen.close()">×</button></div><p>Enter the email used for your Dal profile. Production would send a one-time sign-in link or code.</p><div class="lead-field"><label>Email</label><input id="lgLogin" type="email" autocomplete="email"></div><div class="lead-error" id="lgError"></div><div class="lead-actions"><button class="lead-btn lead-primary" onclick="LeadGen.login()">Continue →</button><button class="lead-btn lead-secondary" onclick="LeadGen.register()">Create profile</button></div>`}
function login(){const e=lgLogin.value.trim().toLowerCase(),all=leads();if(!validEmail(e)){lgError.textContent='Enter a valid email address.';return}if(!all[e]){lgError.textContent='No prototype profile is stored for that email in this browser.';return}localStorage.setItem(ACCOUNT,JSON.stringify(all[e].profile));updateAccountUI();showSaved('Signed in on this device.')}
function showSaved(message){open();const a=account();if(!a){signIn();return}const all=leads(),arr=(all[a.email]?.saved||[]);leadBox.innerHTML=`<div class="lead-top"><div><div class="lead-kicker">My Dal list</div><h2>${esc(a.first)}'s saved results</h2></div><button class="lead-close" onclick="LeadGen.close()">×</button></div>${message?`<p>${esc(message)}</p>`:'<p>Programs and planning results you have kept while exploring.</p>'}<div class="saved-list">${arr.length?arr.map((x,i)=>`<div class="saved-item"><div><b><a href="${esc(x.url)}">${esc(x.label)}</a></b><small>${esc(x.type||'Saved item')}</small></div><button title="Remove" onclick="LeadGen.remove(${i})">×</button></div>`).join(''):'<div class="saved-item"><div><b>Nothing saved yet</b><small>Use Save on a program or planning result and it will appear here.</small></div></div>'}</div><div class="lead-actions"><button class="lead-btn lead-secondary" onclick="LeadGen.signOut()">Sign out</button></div><p class="lead-note">Prototype storage is local to this browser. Production would retrieve these records from the CRM-backed service.</p>`}
function remove(i){const a=account(),all=leads();if(!a||!all[a.email])return;all[a.email].saved.splice(i,1);saveLeads(all);showSaved()}
function signOut(){localStorage.removeItem(ACCOUNT);close();updateAccountUI()}
function markSaved(item){document.querySelectorAll('button,a').forEach(el=>{if(/save/i.test(el.textContent||'')&&!/saved/i.test(el.textContent||'')){if(document.body.dataset.program||location.pathname.includes('marine-biology'))el.textContent='✓ Saved'}})}
function updateAccountUI(){const a=account();document.querySelectorAll('[data-lead-account]').forEach(el=>{el.textContent=a?`👤 ${a.first}`:'Sign in'})}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;const txt=(t.textContent||'').trim();if(t.matches('[data-lead-account]')){e.preventDefault();a=account();a?showSaved():signIn();return}if(t.matches('[data-lead-list]')){e.preventDefault();account()?showSaved():signIn();return}if(/^♡?\s*save\b/i.test(txt)||/save program/i.test(txt)||/save .* to my list/i.test(txt)){e.preventDefault();e.stopImmediatePropagation();save(inferItem(t))}},true);updateAccountUI()}
window.LeadGen={save,signIn,login,register:()=>renderRegister(null),sendCode,verify,showSaved,remove,signOut,close,addItem};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();